### PR TITLE
Blazingly fast!!! 🚀 🚀 🚀

### PR DESCRIPTION
**Pull request by fiorematteo**

### CODE REVIEW

**Comment by MarcoMeinardi** [comment]
https://github.com/MarcoMeinardi/advent-of-code/blob/master/2023/day23/day23_2.cpp#L20 I am perfectly aware that my code is trash, I could have made it better, but it finished computing before I could write an optimized solution and that's all that matter.
Also, you should focus on the 21st day second part instead of doing silly things like these.

One last thing: C++ is way better than Rust.

**Comment by ninomerlino** [comment]
I think the rust implementation is smarter, i would accept the pull if i were you

**Comment by MarcoMeinardi** [comment]
You probably don't know that the problem we are facing is NP-hard, so, no matter how much you try to optimize your solution, in the worst case scenario my solution will be faster (beside beeing much simpler). I know that this is not the worst case scenario and @fiorematteo solution will end faster, but since the sole purpose of this code is to solve today's problem, taking 3 minutes to compute the solution is completely reasonable.

**Comment by ninomerlino** [comment]
cope
imparati rust per una volta

**Comment by MarcoMeinardi** [comment]
Closing this due to @ninomerlino beegin severely brain damaged

**Comment by ninomerlino** [comment]
gonna cancel you on TWITTER
`rm -rdf chino`

**Comment by MarcoMeinardi** [comment]
First of all twitter doesn't exist anymore, you might be referring to what goes under the name of X. In second place, you should learn, not only a real language (in rust you can omit the return keyword, which makes it a non-language), but also refresh your bash (or whatever shell you are using) knowledge, the `-d` flag is implicit if the `-r` flag is present, so you are just wasting a keystroke (go learn vim and play [vimgolf](https://www.vimgolf.com/)). Last but not least, "chino" is not my X nickname, you twitter blue user (yes, I dare using your spells against you).

**Pull request closed without merging**
